#!/bin/sh

escape_value() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

URL=$(escape_value "$1")

SOCKET_PATH="{{.SocketPath}}"

exec nvim --server "$SOCKET_PATH" --remote-expr "v:lua._G._nvrh.open_url(\"$URL\")" > /dev/null 2>&1
