#!/usr/bin/env bash
set -ex

ARCHS=(
  amd64
  arm64
)
OSES=(
  linux
  darwin
  windows
)

cp manifest.json src/

for os in "${OSES[@]}"; do
  for arch in "${ARCHS[@]}"; do
    GOOS="$os" GOARCH="$arch" go build -ldflags "-s -w" -o "dist/$(basename "$PWD")-$os-$arch" ./src/main.go
  done
done

find ./dist -name '*-windows-*' -not -name '*.exe' | while read -r line; do
  mv "$line" "$line.exe"
done
